@startuml

left to right direction
actor "Usuario" as us
actor "Administrador" as ad

usecase "Iniciar sesión" as UC1
usecase "Recuperar contraseña" as UC2
usecase "Modificar contraseña" as UC3
usecase "Cerrar sesión" as UC4
usecase "Registrar usuario" as UC5
usecase "Instalar programa" as UC6

us -- UC1
us -- UC2
us -- UC3
us -- UC4
ad -- UC5
ad -- UC6
ad --|> us

@enduml