@startuml

actor "Ciudadano" as c
actor "Ciudadano extranjero" as ce

usecase "Registra entrada" as UC1
usecase "Tomar huellas" as UC2

c -right- UC1
ce -right- UC2
UC2 .up.> UC1 : <<extend>>
c <|-- ce

@enduml